import {MenuOptionsApi} from "./menu-options.api";
import {FormOptionModel} from "../../models";
import {parseCsv} from "../../utils";

const industryTypesCsv = `Code,Division,Industry ,Strategic Rating,
01.11,Growing of non-perennial crops,"Growing of cereals (except rice), leguminous crops and oil seeds",MEDIUM,
01.12,Growing of non-perennial crops,Growing of rice,LOW,
01.13,Growing of non-perennial crops,"Growing of vegetables and melons, roots and tubers",MEDIUM,
01.14,Growing of non-perennial crops,Growing of sugar cane,LOW,
01.15,Growing of non-perennial crops,Growing of tobacco,HIGH,
01.16,Growing of non-perennial crops,Growing of fibre crops,MEDIUM,
01.19,Growing of non-perennial crops,Growing of other non-perennial crops,MEDIUM,
01.21,Growing of perennial crops,Growing of grapes,MEDIUM,
01.22,Growing of perennial crops,Growing of tropical and subtropical fruits,LOW,
01.23,Growing of perennial crops,Growing of citrus fruits,LOW,
01.24,Growing of perennial crops,Growing of pome fruits and stone fruits,MEDIUM,
01.25,Growing of perennial crops,Growing of other tree and bush fruits and nuts,MEDIUM,
01.26,Growing of perennial crops,Growing of oleaginous fruits,LOW,
01.27,Growing of perennial crops,Growing of beverage crops,LOW,
24.41,Manufacture of basic metals,Precious metals production,HIGH,
01.29,Growing of perennial crops,Growing of other perennial crops,MEDIUM,
01.30,Plant propagation,Plant propagation,MEDIUM,
01.41,Animal production,Raising of dairy cattle,LOW,
01.42,Animal production,Raising of other cattle and buffaloes,LOW,
01.43,Animal production,Raising of horses and other equines,LOW,
01.44,Animal production,Raising of camels and camelids,LOW,
01.45,Animal production,Raising of sheep and goats,LOW,
01.46,Animal production,Raising of swine/pigs,LOW,
01.47,Animal production,Raising of poultry,LOW,
01.49,Animal production,Raising of other animals,MEDIUM,
01.50,Mixed Farming,Mixed farming,MEDIUM,
01.61,Support activities to agriculture and post-harvest crop activities,Support activities for crop production,MEDIUM,
01.63,Support activities to agriculture and post-harvest crop activities,Post-harvest crop activities,MEDIUM,
01.64,Support activities to agriculture and post-harvest crop activities,Seed processing for propagation,LOW,
01.70,"Hunting, trapping and related service activities","Hunting, trapping and related service activities",AUTO-HIGH,
02.10,Forestry and logging,Silviculture and other forestry activities,MEDIUM,
02.20,Forestry and logging,Logging,MEDIUM,
02.30,Forestry and logging,Gathering of wild growing non-wood products,MEDIUM,
02.40,Forestry and logging,Support services to forestry,MEDIUM,
03.11,Mining and Quarrying,Marine fishing,MEDIUM,
03.12,Mining and Quarrying,Freshwater fishing,MEDIUM,
03.21,Mining and Quarrying,Marine aquaculture,MEDIUM,
03.22,Mining and Quarrying,Freshwater aquaculture,MEDIUM,
26.52,"Manufacture of computer, electronic and optical products",Manufacture of watches and clocks,LOW,
32.12,Other manufacturing,Manufacture of jewellery and related articles,HIGH,
32.13,Other manufacturing,Manufacture of imitation jewellery and related articles,LOW,
46.35,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of tobacco products,HIGH,
47.26,"Retail trade, except of motor vehicles and motorcycles",Retail sale of tobacco products in specialised stores,HIGH,
88.10,Social work activities without accommodation,Social work activities without accommodation for the elderly and disabled,LOW,
46.71/1,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of petroleum and petroleum products,HIGH,
47.78/1,"Retail trade, except of motor vehicles and motorcycles",Retail sale in commercial art galleries,AUTO-HIGH,
47.79/1,"Retail trade, except of motor vehicles and motorcycles","Retail sale of antiques including antique books, in stores",AUTO-HIGH,
08.92,Other mining and quarrying,Extraction of peat,MEDIUM,
08.93,Other mining and quarrying,Extraction of salt,MEDIUM,
87.30,Residential care activities,Residential care activities for the elderly and disabled,HIGH,
05.20,Mining of coal and lignite,Mining of lignite,AUTO-HIGH,
06.10,Extraction of crude petroleum and natural gas,Extraction of crude petroleum,AUTO-HIGH,
10.11,Manufacture of food products,Processing and preserving of meat,MEDIUM,
10.12,Manufacture of food products,Processing and preserving of poultry meat,MEDIUM,
10.13,Manufacture of food products,Production of meat and poultry meat products,MEDIUM,
10.20,Manufacture of food products,"Processing and preserving of fish, crustaceans and molluscs",MEDIUM,
10.31,Manufacture of food products,Processing and preserving of potatoes,MEDIUM,
10.32,Manufacture of food products,Manufacture of fruit and vegetable juice,LOW,
10.39,Manufacture of food products,Other processing and preserving of fruit and vegetables,MEDIUM,
10.41,Manufacture of food products,Manufacture of oils and fats,LOW,
10.42,Manufacture of food products,Manufacture of margarine and similar edible fats,LOW,
10.52,Manufacture of food products,Manufacture of ice cream,LOW,
10.62,Manufacture of food products,Manufacture of starches and starch products,LOW,
10.71,Manufacture of food products,Manufacture of bread; manufacture of fresh pastry goods and cakes,LOW,
10.72,Manufacture of food products,Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes,LOW,
10.73,Manufacture of food products,"Manufacture of macaroni, noodles, couscous and similar farinaceous products",MEDIUM,
10.81,Manufacture of food products,Manufacture of sugar,LOW,
10.84,Manufacture of food products,Manufacture of condiments and seasonings,LOW,
10.85,Manufacture of food products,Manufacture of prepared meals and dishes,MEDIUM,
10.86,Manufacture of food products,Manufacture of homogenised food preparations and dietetic food,MEDIUM,
10.89,Manufacture of food products,Manufacture of other food products n.e.c.,MEDIUM,
10.91,Manufacture of food products,Manufacture of prepared feeds for farm animals,MEDIUM,
10.92,Manufacture of food products,Manufacture of prepared pet foods,MEDIUM,
11.01,Manufacture of beverages,"Distilling, rectifying and blending of spirits",LOW,
11.02,Manufacture of beverages,Manufacture of wine from grape,LOW,
11.03,Manufacture of beverages,Manufacture of cider and other fruit wines,LOW,
11.04,Manufacture of beverages,Manufacture of other non-distilled fermented beverages,LOW,
11.05,Manufacture of beverages,Manufacture of beer,LOW,
11.06,Manufacture of beverages,Manufacture of malt,LOW,
11.07,Manufacture of beverages,Manufacture of soft drinks; production of mineral waters and other bottled waters,LOW,
12.00,Manufacture of tobacco products,Manufacture of tobacco products,HIGH,
13.10,Manufacture of textiles,Preparation and spinning of textile fibres,LOW,
13.20,Manufacture of textiles,Weaving of textiles,LOW,
13.30,Manufacture of textiles,Finishing of textiles,LOW,
13.91,Manufacture of textiles,Manufacture of knitted and crocheted fabrics,LOW,
13.94,Manufacture of textiles,"Manufacture of cordage, rope, twine and netting",LOW,
13.95,Manufacture of textiles,"Manufacture of non-wovens and articles made from non-wovens, except apparel",LOW,
13.96,Manufacture of textiles,Manufacture of other technical and industrial textiles,LOW,
13.99,Manufacture of textiles,Manufacture of other textiles n.e.c.,LOW,
14.11,Manufacture of wearing apparel,Manufacture of leather clothes,LOW,
14.12,Manufacture of wearing apparel,Manufacture of workwear,LOW,
14.19,Manufacture of wearing apparel,Manufacture of other wearing apparel and accessories,MEDIUM,
14.20,Manufacture of wearing apparel,Manufacture of articles of fur,MEDIUM,
14.31,Manufacture of wearing apparel,Manufacture of knitted and crocheted hosiery,LOW,
14.39,Manufacture of wearing apparel,Manufacture of other knitted and crocheted apparel,LOW,
15.11,Manufacture of leather and related products,Tanning and dressing of leather; dressing and dyeing of fur,MEDIUM,
15.12,Manufacture of leather and related products,"Manufacture of luggage, handbags and the like, saddlery and harness",LOW,
15.20,Manufacture of leather and related products,Manufacture of footwear,LOW,
16.10,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",Sawmilling and planing of wood,LOW,
16.21,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",Manufacture of veneer sheets and wood-based panels,LOW,
16.22,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",Manufacture of assembled parquet floors,LOW,
16.23,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",Manufacture of other builders' carpentry and joinery,LOW,
16.24,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",Manufacture of wooden containers,LOW,
16.29,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials","Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials",LOW,
17.11,Manufacture of paper and paper products,Manufacture of pulp,LOW,
17.12,Manufacture of paper and paper products,Manufacture of paper and paperboard,LOW,
17.22,Manufacture of paper and paper products,Manufacture of household and sanitary goods and of toilet requisites,LOW,
17.23,Manufacture of paper and paper products,Manufacture of paper stationery,LOW,
17.24,Manufacture of paper and paper products,Manufacture of wallpaper,LOW,
17.29,Manufacture of paper and paper products,Manufacture of other articles of paper and paperboard,LOW,
18.11,Printing and reproduction of recorded media,Printing of newspapers,LOW,
18.13,Printing and reproduction of recorded media,Pre-press and pre-media services,LOW,
18.14,Printing and reproduction of recorded media,Binding and related services,LOW,
19.10,Manufacture of coke and refined petroleum products,Manufacture of coke oven products,LOW,
20.11,Manufacture of chemicals and chemical products,Manufacture of industrial gases,AUTO-HIGH,
20.12,Manufacture of chemicals and chemical products,Manufacture of dyes and pigments,LOW,
06.20,Extraction of crude petroleum and natural gas,Extraction of natural gas,AUTO-HIGH,
20.14,Manufacture of chemicals and chemical products,Manufacture of other organic basic chemicals (Med),AUTO-HIGH,
20.15,Manufacture of chemicals and chemical products,Manufacture of fertilisers and nitrogen compounds,AUTO-HIGH,
20.16,Manufacture of chemicals and chemical products,Manufacture of plastics in primary forms,LOW,
20.17,Manufacture of chemicals and chemical products,Manufacture of synthetic rubber in primary forms,LOW,
87.90,Residential care activities,Other residential care activities,HIGH,
20.42,Manufacture of chemicals and chemical products,Manufacture of perfumes and toilet preparations,LOW,
07.10,Mining of metal ores,Mining of iron ores,AUTO-HIGH,
20.52,Manufacture of chemicals and chemical products,Manufacture of glues,LOW,
20.53,Manufacture of chemicals and chemical products,Manufacture of essential oils,LOW,
20.59,Manufacture of chemicals and chemical products,Manufacture of other chemical products n.e.c.,AUTO-HIGH,
20.60,Manufacture of chemicals and chemical products,Manufacture of man-made fibres,LOW,
21.10,Manufacture of basic pharmaceutical products and pharmaceutical preparations,Manufacture of basic pharmaceutical products,AUTO-HIGH,
07.21,Mining of metal ores,Mining of uranium and thorium ores,AUTO-HIGH,
22.11,Manufacture of rubber and plastic products,Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres,LOW,
22.19,Manufacture of rubber and plastic products,Manufacture of other rubber products,LOW,
22.21,Manufacture of rubber and plastic products,"Manufacture of plastic plates, sheets, tubes and profiles",LOW,
22.22,Manufacture of rubber and plastic products,Manufacture of plastic packing goods,LOW,
22.23,Manufacture of rubber and plastic products,Manufacture of builders' ware of plastic,LOW,
22.29,Manufacture of rubber and plastic products,Manufacture of other plastic products,LOW,
23.11,Manufacture of other non-metallic mineral products,Manufacture of flat glass,LOW,
23.12,Manufacture of other non-metallic mineral products,Shaping and processing of flat glass,LOW,
23.13,Manufacture of other non-metallic mineral products,Manufacture of hollow glass,LOW,
23.14,Manufacture of other non-metallic mineral products,Manufacture of glass fibres,LOW,
23.19,Manufacture of other non-metallic mineral products,"Manufacture and processing of other glass, including technical glassware",LOW,
23.20,Manufacture of other non-metallic mineral products,Manufacture of refractory products,LOW,
23.31,Manufacture of other non-metallic mineral products,Manufacture of ceramic tiles and flags,LOW,
23.32,Manufacture of other non-metallic mineral products,"Manufacture of bricks, tiles and construction products, in baked clay",LOW,
23.41,Manufacture of other non-metallic mineral products,Manufacture of ceramic household and ornamental articles,LOW,
23.42,Manufacture of other non-metallic mineral products,Manufacture of ceramic sanitary fixtures,LOW,
23.43,Manufacture of other non-metallic mineral products,Manufacture of ceramic insulators and insulating fittings,LOW,
23.44,Manufacture of other non-metallic mineral products,Manufacture of other technical ceramic products,LOW,
23.49,Manufacture of other non-metallic mineral products,Manufacture of other ceramic products,LOW,
23.51,Manufacture of other non-metallic mineral products,Manufacture of cement,LOW,
23.52,Manufacture of other non-metallic mineral products,Manufacture of lime and plaster,LOW,
23.61,Manufacture of other non-metallic mineral products,Manufacture of concrete products for construction purposes,LOW,
23.62,Manufacture of other non-metallic mineral products,Manufacture of plaster products for construction purposes,LOW,
23.63,Manufacture of other non-metallic mineral products,Manufacture of ready-mixed concrete,LOW,
23.64,Manufacture of other non-metallic mineral products,Manufacture of mortars,LOW,
23.65,Manufacture of other non-metallic mineral products,Manufacture of fibre cement,LOW,
23.69,Manufacture of other non-metallic mineral products,"Manufacture of other articles of concrete, plaster and cement",LOW,
23.70,Manufacture of other non-metallic mineral products,"Cutting, shaping and finishing of stone",LOW,
23.91,Manufacture of other non-metallic mineral products,Production of abrasive products,LOW,
23.99,Manufacture of other non-metallic mineral products,Manufacture of other non-metallic mineral products n.e.c.,LOW,
24.10,Manufacture of basic metals,Manufacture of basic iron and steel and of ferro-alloys,LOW,
24.20,Manufacture of basic metals,"Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",LOW,
24.31,Manufacture of basic metals,Cold drawing of bars,LOW,
24.32,Manufacture of basic metals,Cold rolling of narrow strip,LOW,
24.33,Manufacture of basic metals,Cold forming or folding,LOW,
24.34,Manufacture of basic metals,Cold drawing of wire,LOW,
07.29,Mining of metal ores,Mining of other non-ferrous metal ores,AUTO-HIGH,
87.10,Residential care activities,Residential nursing care activities,HIGH,
24.43,Manufacture of basic metals,"Lead, zinc and tin production",LOW,
24.44,Manufacture of basic metals,Copper production,MEDIUM,
24.45,Manufacture of basic metals,Other non-ferrous metal production,LOW,
87.20,Residential care activities,"Residential care activities for learning disabilities, mental health and substance abuse",HIGH,
24.51,Manufacture of basic metals,Casting of iron,LOW,
24.52,Manufacture of basic metals,Casting of steel,LOW,
24.53,Manufacture of basic metals,Casting of light metals,LOW,
64.99/9,"Financial service activities, except insurance and pension funding","Other financial service activities, except insurance and pension funding, (not including security dealing on own account and factoring) n.e.c.",MEDIUM,
25.11,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of metal structures and parts of structures,LOW,
25.12,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of doors and windows of metal,LOW,
25.21,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of central heating radiators and boilers,LOW,
25.29,"Manufacture of fabricated metal products, except machinery and equipment","Manufacture of other tanks, reservoirs and containers of metal",LOW,
08.91,Other mining and quarrying,Mining of chemical and fertiliser minerals,AUTO-HIGH,
08.99,Other mining and quarrying,Other mining and quarrying n.e.c.,AUTO-HIGH,
25.50,"Manufacture of fabricated metal products, except machinery and equipment","Forging, pressing, stamping and roll-forming of metal; powder metallurgy",LOW,
25.61,"Manufacture of fabricated metal products, except machinery and equipment",Treatment and coating of metals,LOW,
64.19/1,"Financial service activities, except insurance and pension funding",Banks,LOW,
25.71,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of cutlery,LOW,
25.72,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of locks and hinges,LOW,
64.19,"Financial service activities, except insurance and pension funding",Credit Unions and other monetary institutions,HIGH,
25.91,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of steel drums and similar containers,LOW,
25.92,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of light metal packaging,LOW,
25.93,"Manufacture of fabricated metal products, except machinery and equipment","Manufacture of wire products, chain and springs",LOW,
25.94,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of fasteners and screw machine products,LOW,
25.99,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of other fabricated metal products n.e.c.,LOW,
09.10,Mining support service activities,Support activities for petroleum and natural gas extraction,AUTO-HIGH,
09.90,Mining support service activities,Support activities for other mining and quarrying,AUTO-HIGH,
20.13,Manufacture of chemicals and chemical products,Manufacture of other inorganic basic chemicals (Med),AUTO-HIGH,
26.40,"Manufacture of computer, electronic and optical products",Manufacture of consumer electronics,LOW,
20.51,Manufacture of chemicals and chemical products,Manufacture of explosives,AUTO-HIGH,
21.20,Manufacture of basic pharmaceutical products and pharmaceutical preparations,Manufacture of pharmaceutical preparations,AUTO-HIGH,
26.80,"Manufacture of computer, electronic and optical products",Manufacture of magnetic and optical media,MEDIUM,
27.11,Manufacture of electrical equipment,"Manufacture of electric motors, generators and transformers",LOW,
27.12,Manufacture of electrical equipment,Manufacture of electricity distribution and control apparatus,LOW,
27.20,Manufacture of electrical equipment,Manufacture of batteries and accumulators,LOW,
24.46,Manufacture of basic metals,Processing of nuclear fuel,AUTO-HIGH,
27.32,Manufacture of electrical equipment,Manufacture of other electronic and electric wires and cables,LOW,
64.11,"Financial service activities, except insurance and pension funding",Central banking,LOW,
27.40,Manufacture of electrical equipment,Manufacture of electric lighting equipment,LOW,
27.51,Manufacture of electrical equipment,Manufacture of electric domestic appliances,LOW,
27.52,Manufacture of electrical equipment,Manufacture of non-electric domestic appliances,LOW,
80.10,Security and investigation activities,Private security activities,HIGH,
25.40,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of weapons and ammunition,AUTO-HIGH,
28.12,Manufacture of machinery and equipment n.e.c.,Manufacture of fluid power equipment,MEDIUM,
28.14,Manufacture of machinery and equipment n.e.c.,Manufacture of other taps and valves,LOW,
51.22,Air transport,Space transport,HIGH,
28.21,Manufacture of machinery and equipment n.e.c.,"Manufacture of ovens, furnaces and furnace burners",LOW,
28.22,Manufacture of machinery and equipment n.e.c.,Manufacture of lifting and handling equipment,LOW,
28.23,Manufacture of machinery and equipment n.e.c.,Manufacture of office machinery and equipment (except computers and peripheral equipment),LOW,
28.24,Manufacture of machinery and equipment n.e.c.,Manufacture of power-driven hand tools,LOW,
28.25,Manufacture of machinery and equipment n.e.c.,Manufacture of non-domestic cooling and ventilation equipment,LOW,
28.29,Manufacture of machinery and equipment n.e.c.,Manufacture of other general-purpose machinery n.e.c.,MEDIUM,
28.41,Manufacture of machinery and equipment n.e.c.,Manufacture of metal forming machinery,LOW,
28.49,Manufacture of machinery and equipment n.e.c.,Manufacture of other machine tools,LOW,
28.91,Manufacture of machinery and equipment n.e.c.,Manufacture of machinery for metallurgy,LOW,
28.93,Manufacture of machinery and equipment n.e.c.,"Manufacture of machinery for food, beverage and tobacco processing",MEDIUM,
28.94,Manufacture of machinery and equipment n.e.c.,"Manufacture of machinery for textile, apparel and leather production",LOW,
28.95,Manufacture of machinery and equipment n.e.c.,Manufacture of machinery for paper and paperboard production,LOW,
28.96,Manufacture of machinery and equipment n.e.c.,Manufacture of plastics and rubber machinery,LOW,
47.73,"Retail trade, except of motor vehicles and motorcycles",Dispensing chemist in specialised stores,LOW,
29.10,"Manufacture of motor vehicles, trailers and semi-trailers",Manufacture of motor vehicles,LOW,
29.31,"Manufacture of motor vehicles, trailers and semi-trailers",Manufacture of electrical and electronic equipment for motor vehicles,HIGH,
29.32,"Manufacture of motor vehicles, trailers and semi-trailers",Manufacture of other parts and accessories for motor vehicles,MEDIUM,
46.76,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of other intermediate products,MEDIUM,
30.12,Manufacture of other transport equipment,Building of pleasure and sporting boats,LOW,
30.20,Manufacture of other transport equipment,Manufacture of railway locomotives and rolling stock,LOW,
66.12,Activities auxiliary to financial services and insurance activities,Security and commodity contracts brokerage,MEDIUM,
30.40,Manufacture of other transport equipment,Manufacture of military fighting vehicles,AUTO-HIGH,
30.91,Manufacture of other transport equipment,Manufacture of motorcycles,LOW,
30.92,Manufacture of other transport equipment,Manufacture of bicycles and invalid carriages,LOW,
30.99,Manufacture of other transport equipment,Manufacture of other transport equipment n.e.c.,LOW,
31.01,Manufacture of furniture,Manufacture of office and shop furniture,LOW,
31.02,Manufacture of furniture,Manufacture of kitchen furniture,LOW,
31.03,Manufacture of furniture,Manufacture of mattresses,LOW,
31.09,Manufacture of furniture,Manufacture of other furniture,LOW,
94.91,Activities of membership organisations,Activities of religious organisations,HIGH,
26.60,"Manufacture of computer, electronic and optical products",Manufacture of irradiation electromedical and electrotherapeutic equipment,AUTO-HIGH,
96.09,Other personal service activities,Other personal service activities n.e.c.,MEDIUM,
32.20,Other manufacturing,Manufacture of musical instruments,LOW,
32.30,Other manufacturing,Manufacture of sports goods,LOW,
32.50,Other manufacturing,Manufacture of medical and dental instruments and supplies,MEDIUM,
32.91,Other manufacturing,Manufacture of brooms and brushes,LOW,
32.99,Other manufacturing,Other manufacturing n.e.c.,MEDIUM,
33.11,Repair and installation of machinery and equipment,Repair of fabricated metal products,HIGH,
33.12,Repair and installation of machinery and equipment,Repair of machinery,LOW,
33.13,Repair and installation of machinery and equipment,Repair of electronic and optical equipment,MEDIUM,
33.14,Repair and installation of machinery and equipment,Repair of electrical equipment,MEDIUM,
01.28,Growing of perennial crops,Growing of spices aromatic drug and pharmaceutical crops,MEDIUM,
28.13/1,Manufacture of machinery and equipment n.e.c.,Manufacture of pumps,MEDIUM,
33.17,Repair and installation of machinery and equipment,Repair and maintenance of other transport equipment,LOW,
33.19,Repair and installation of machinery and equipment,Repair of other equipment,LOW,
33.20,Repair and installation of machinery and equipment,Installation of industrial machinery and equipment,LOW,
35.11,"Electricity, gas, steam and air conditioning supply",Production of electricity,LOW,
35.12,"Electricity, gas, steam and air conditioning supply",Transmission of electricity,MEDIUM,
35.13,"Electricity, gas, steam and air conditioning supply",Distribution of electricity,MEDIUM,
35.14,"Electricity, gas, steam and air conditioning supply",Trade of electricity,MEDIUM,
35.21,"Electricity, gas, steam and air conditioning supply",Manufacture of gas,AUTO-HIGH,
35.22,"Electricity, gas, steam and air conditioning supply",Distribution of gaseous fuels through mains,AUTO-HIGH,
35.23,"Electricity, gas, steam and air conditioning supply",Trade of gas through mains,AUTO-HIGH,
35.30,"Electricity, gas, steam and air conditioning supply",Steam and air conditioning supply,LOW,
36.00,"Water collection, treatment and supply","Water collection, treatment and supply",LOW,
37.00,Sewerage,Sewerage,LOW,
38.11,"Waste collection, treatment and disposal activities; materials recovery",Collection of non-hazardous waste,LOW,
38.12,"Waste collection, treatment and disposal activities; materials recovery",Collection of hazardous waste,AUTO-HIGH,
38.21,"Waste collection, treatment and disposal activities; materials recovery",Treatment and disposal of non-hazardous waste,LOW,
38.22,"Waste collection, treatment and disposal activities; materials recovery",Treatment and disposal of hazardous waste,AUTO-HIGH,
38.31,"Waste collection, treatment and disposal activities; materials recovery",Dismantling of wrecks,MEDIUM,
38.32,"Waste collection, treatment and disposal activities; materials recovery",Recovery of sorted materials,HIGH,
39.00,Remediation activities and other waste management services,Remediation activities and other waste management services,LOW,
41.10,Construction of buildings,Development of building projects,MEDIUM,
42.11,Civil engineering,Construction of roads and motorways,MEDIUM,
42.12,Civil engineering,Construction of railways and underground railways,MEDIUM,
42.13,Civil engineering,Construction of bridges and tunnels,MEDIUM,
42.21,Civil engineering,Construction of utility projects for fluids,MEDIUM,
42.22,Civil engineering,Construction of utility projects for electricity and telecommunications,MEDIUM,
42.91,Civil engineering,Construction of water projects,MEDIUM,
42.99,Civil engineering,Construction of other civil engineering projects n.e.c.,MEDIUM,
43.11,Specialised construction activities,Demolition,MEDIUM,
43.12,Specialised construction activities,Site preparation,MEDIUM,
43.13,Specialised construction activities,Test drilling and boring,MEDIUM,
43.21,Specialised construction activities,Electrical installation,LOW,
43.22,Specialised construction activities,"Plumbing, heat and air-conditioning installation",LOW,
43.29,Specialised construction activities,Other construction installation,MEDIUM,
43.31,Specialised construction activities,Plastering,MEDIUM,
43.32,Specialised construction activities,Joinery installation,LOW,
43.33,Specialised construction activities,Floor and wall covering,MEDIUM,
43.39,Specialised construction activities,Other building completion and finishing,MEDIUM,
43.91,Specialised construction activities,Roofing activities,LOW,
45.19,Wholesale and retail trade and repair of motor vehicles and motorcycles,Sale of other motor vehicles,HIGH,
45.20,Wholesale and retail trade and repair of motor vehicles and motorcycles,Maintenance and repair of motor vehicles,LOW,
45.31,Wholesale and retail trade and repair of motor vehicles and motorcycles,Wholesale trade of motor vehicle parts and accessories,MEDIUM,
45.32,Wholesale and retail trade and repair of motor vehicles and motorcycles,Retail trade of motor vehicle parts and accessories,MEDIUM,
45.40,Wholesale and retail trade and repair of motor vehicles and motorcycles,"Sale, maintenance and repair of motorcycles and related parts and accessories",MEDIUM,
46.11,"Wholesale trade, except of motor vehicles and motorcycles","Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods",LOW,
46.12,"Wholesale trade, except of motor vehicles and motorcycles","Agents involved in the sale of fuels, ores, metals and industrial chemicals",AUTO-HIGH,
46.13,"Wholesale trade, except of motor vehicles and motorcycles",Agents involved in the sale of timber and building materials,LOW,
27.31,Manufacture of electrical equipment,Manufacture of fibre optic cables,MEDIUM,
46.15,"Wholesale trade, except of motor vehicles and motorcycles","Agents involved in the sale of furniture, household goods, hardware and ironmongery",LOW,
46.16,"Wholesale trade, except of motor vehicles and motorcycles","Agents involved in the sale of textiles, clothing, fur, footwear and leather goods",HIGH,
46.17,"Wholesale trade, except of motor vehicles and motorcycles","Agents involved in the sale of food, beverages and tobacco",MEDIUM,
46.18,"Wholesale trade, except of motor vehicles and motorcycles",Agents specialised in the sale of other particular products,LOW,
46.19,"Wholesale trade, except of motor vehicles and motorcycles",Agents involved in the sale of a variety of goods,LOW,
46.21,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",MEDIUM,
46.22,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of flowers and plants,LOW,
46.23,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of live animals,HIGH,
46.24,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of hides, skins and leather",MEDIUM,
46.31,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of fruit and vegetables,LOW,
46.32,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of meat and meat products,LOW,
46.33,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of dairy products, eggs and edible oils and fats",LOW,
27.33,Manufacture of electrical equipment,Manufacture of wiring devices,AUTO-HIGH,
46.36,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of sugar and chocolate and sugar confectionery,LOW,
46.37,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of coffee, tea, cocoa and spices",LOW,
46.38,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of other food, including fish, crustaceans and molluscs",LOW,
46.39,"Wholesale trade, except of motor vehicles and motorcycles","Non-specialised wholesale of food, beverages and tobacco",MEDIUM,
46.41,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of textiles,LOW,
46.42,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of clothing and footwear,MEDIUM,
46.44,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of china and glassware and cleaning materials,LOW,
46.45,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of perfume and cosmetics,LOW,
46.51,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of computers, computer peripheral equipment and software",HIGH,
46.47,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of furniture, carpets and lighting equipment",LOW,
46.48,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of watches and jewellery,AUTO-HIGH,
47.76,"Retail trade, except of motor vehicles and motorcycles","Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores",HIGH,
46.52,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of electronic and telecommunications equipment and parts,HIGH,
46.61,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of agricultural machinery, equipment and supplies",LOW,
46.62,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of machine tools,LOW,
46.63,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of mining, construction and civil engineering machinery",LOW,
46.64,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of machinery for the textile industry and of sewing and knitting machines,LOW,
46.65,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of office furniture,LOW,
46.66,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of other office machinery and equipment,LOW,
46.69,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of other machinery and equipment,LOW,
26.30/1,"Manufacture of computer, electronic and optical products",Manufacture of telegraph and telephone apparatus and equipment,MEDIUM,
46.73,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of wood, construction materials and sanitary equipment",LOW,
46.74,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of hardware, plumbing and heating equipment and supplies",LOW,
47.42/9,"Retail trade, except of motor vehicles and motorcycles","Retail sale of telecommunications equipment (other than mobile telephones) n.e.c., in specialised stores",HIGH,
28.15,Manufacture of machinery and equipment n.e.c.,"Manufacture of bearings, gears, gearing and driving elements",AUTO-HIGH,
46.77,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of waste and scrap,HIGH,
46.90,"Wholesale trade, except of motor vehicles and motorcycles",Non-specialised wholesale trade,LOW,
47.11,"Retail trade, except of motor vehicles and motorcycles","Retail sale in non-specialised stores with food, beverages or tobacco predominating",MEDIUM,
47.19,"Retail trade, except of motor vehicles and motorcycles",Other retail sale in non-specialised stores,LOW,
47.21,"Retail trade, except of motor vehicles and motorcycles",Retail sale of fruit and vegetables in specialised stores,LOW,
47.22,"Retail trade, except of motor vehicles and motorcycles",Retail sale of meat and meat products in specialised stores,LOW,
47.23,"Retail trade, except of motor vehicles and motorcycles","Retail sale of fish, crustaceans and molluscs in specialised stores",LOW,
47.24,"Retail trade, except of motor vehicles and motorcycles","Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores",LOW,
47.25,"Retail trade, except of motor vehicles and motorcycles",Retail sale of beverages in specialised stores,MEDIUM,
47.78/9,"Retail trade, except of motor vehicles and motorcycles","Other retail sale of new goods in specialised stores (other than by opticians or commercial art galleries), n.e.c",MEDIUM,
47.29,"Retail trade, except of motor vehicles and motorcycles",Other retail sale of food in specialised stores,MEDIUM,
47.30,"Retail trade, except of motor vehicles and motorcycles",Retail sale of automotive fuel in specialised stores,LOW,
47.41,"Retail trade, except of motor vehicles and motorcycles","Retail sale of computers, peripheral units and software in specialised stores",MEDIUM,
47.43,"Retail trade, except of motor vehicles and motorcycles",Retail sale of audio and video equipment in specialised stores,MEDIUM,
47.51,"Retail trade, except of motor vehicles and motorcycles",Retail sale of textiles in specialised stores,LOW,
47.52,"Retail trade, except of motor vehicles and motorcycles","Retail sale of hardware, paints and glass in specialised stores",LOW,
47.53,"Retail trade, except of motor vehicles and motorcycles","Retail sale of carpets, rugs, wall and floor coverings in specialised stores",LOW,
47.54,"Retail trade, except of motor vehicles and motorcycles",Retail sale of electrical household appliances in specialised stores,LOW,
47.61,"Retail trade, except of motor vehicles and motorcycles",Retail sale of books in specialised stores,LOW,
47.62,"Retail trade, except of motor vehicles and motorcycles",Retail sale of newspapers and stationery in specialised stores,LOW,
47.63,"Retail trade, except of motor vehicles and motorcycles",Retail sale of music and video recordings in specialised stores,LOW,
47.64,"Retail trade, except of motor vehicles and motorcycles",Retail sale of sporting equipment in specialised stores,LOW,
47.65,"Retail trade, except of motor vehicles and motorcycles",Retail sale of games and toys in specialised stores,LOW,
47.71,"Retail trade, except of motor vehicles and motorcycles",Retail sale of clothing in specialised stores,MEDIUM,
32.11,Other manufacturing,Striking of coins,AUTO-HIGH,
47.75,"Retail trade, except of motor vehicles and motorcycles",Retail sale of cosmetic and toilet articles in specialised stores,LOW,
24.42,Manufacture of basic metals,Aluminium production,MEDIUM,
47.77,"Retail trade, except of motor vehicles and motorcycles",Retail sale of watches and jewellery in specialised stores,AUTO-HIGH,
47.81,"Retail trade, except of motor vehicles and motorcycles","Retail sale via stalls and markets of food, beverages and tobacco products",HIGH,
47.82,"Retail trade, except of motor vehicles and motorcycles","Retail sale via stalls and markets of textiles, clothing and footwear",LOW,
47.89,"Retail trade, except of motor vehicles and motorcycles",Retail sale via stalls and markets of other goods,LOW,
47.91,"Retail trade, except of motor vehicles and motorcycles",Retail sale via mail order houses or via Internet,MEDIUM,
47.99,"Retail trade, except of motor vehicles and motorcycles","Other retail sale not in stores, stalls or markets",MEDIUM,
49.10,Land transport and transport via pipelines,"Passenger rail transport, interurban",LOW,
49.20,Land transport and transport via pipelines,Freight rail transport,MEDIUM,
49.32,Land transport and transport via pipelines,Taxi operation,MEDIUM,
49.39,Land transport and transport via pipelines,Other passenger land transport n.e.c.,MEDIUM,
49.41,Land transport and transport via pipelines,Freight transport by road,MEDIUM,
49.42,Land transport and transport via pipelines,Removal services,LOW,
46.46,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of pharmaceutical goods,AUTO-HIGH,
50.10,Water transport,Sea and coastal passenger water transport,MEDIUM,
50.20,Water transport,Sea and coastal freight water transport,MEDIUM,
50.30,Water transport,Inland passenger water transport,MEDIUM,
50.40,Water transport,Inland freight water transport,MEDIUM,
51.21,Air transport,Freight air transport,MEDIUM,
33.15,Repair and installation of machinery and equipment,Repair and maintenance of ships and boats,MEDIUM,
52.22,Warehousing and support activities for transportation,Service activities incidental to water transportation,MEDIUM,
52.23,Warehousing and support activities for transportation,Service activities incidental to air transportation,MEDIUM,
52.29,Warehousing and support activities for transportation,Other transportation support activities,MEDIUM,
53.10,Postal and courier activities,Postal activities under universal service obligation,LOW,
55.10,Accommodation,Hotels and similar accommodation,MEDIUM,
55.30,Accommodation,"Camping grounds, recreational vehicle parks and trailer parks",LOW,
55.90,Accommodation,Other accommodation,MEDIUM,
56.21,Accommodation,Event catering activities,MEDIUM,
56.29,Accommodation,Other food service activities,MEDIUM,
58.11,Publishing activities,Book publishing,LOW,
58.12,Publishing activities,Publishing of directories and mailing lists,LOW,
58.13,Publishing activities,Publishing of newspapers,LOW,
58.19,Publishing activities,Other publishing activities,LOW,
58.21,Publishing activities,Publishing of computer games,LOW,
58.29,Publishing activities,Other software publishing,LOW,
59.12,"Motion picture, video and television programme production, sound recording and music publishing activites","Motion picture, video and television programme post-production activities",LOW,
59.14,"Motion picture, video and television programme production, sound recording and music publishing activites",Motion picture projection activities,LOW,
59.20,"Motion picture, video and television programme production, sound recording and music publishing activites",Sound recording and music publishing activities,LOW,
60.10,Programming and broadcasting activities,Radio broadcasting,LOW,
60.20,Programming and broadcasting activities,Television programming and broadcasting activities,LOW,
61.10,Telecommunications,Wired telecommunications activities,MEDIUM,
61.20,Telecommunications,Wireless telecommunications activities,MEDIUM,
61.30,Telecommunications,Satellite telecommunications activities,MEDIUM,
33.16,Repair and installation of machinery and equipment,Repair and maintenance of aircraft and spacecraft,HIGH,
62.02,"Computer programming, consultancy and related activities",Computer consultancy activities,LOW,
62.03,"Computer programming, consultancy and related activities",Computer facilities management activities,LOW,
62.09,"Computer programming, consultancy and related activities",Other information technology and computer service activities,LOW,
63.11,Information service activities,"Data processing, hosting and related activities",LOW,
63.12,Information service activities,Web portals,LOW,
63.91,Information service activities,News agencies activities of,LOW,
63.99,Information service activities,Other information service activities n.e.c.,LOW,
46.72,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of metals and metal ores,AUTO-HIGH,
25.62,"Manufacture of fabricated metal products, except machinery and equipment",Machining,MEDIUM,
64.91,"Financial service activities, except insurance and pension funding",Financial leasing,LOW,
65.11,"Insurance, reinsurance and pension funding, except compulsory social security",Life insurance,LOW,
65.12,"Insurance, reinsurance and pension funding, except compulsory social security",Non-life insurance,LOW,
65.30,"Insurance, reinsurance and pension funding, except compulsory social security",Pension funding,LOW,
66.11,Activities auxiliary to financial services and insurance activities,Administration of financial markets,LOW,
25.73,"Manufacture of fabricated metal products, except machinery and equipment",Manufacture of tools,MEDIUM,
66.19,Activities auxiliary to financial services and insurance activities,"Other activities auxiliary to financial services, except insurance and pension funding",MEDIUM,
66.21,Activities auxiliary to financial services and insurance activities,Risk and damage evaluation,LOW,
66.22,Activities auxiliary to financial services and insurance activities,Activities of insurance agents and brokers,LOW,
66.29,Activities auxiliary to financial services and insurance activities,Other activities auxiliary to insurance and pension funding,LOW,
66.30,Activities auxiliary to financial services and insurance activities,Fund management activities,MEDIUM,
68.10,Real estate activities,Buying and selling of own real estate,HIGH,
68.31,Real estate activities,Real estate agencies,HIGH,
68.32,Real estate activities,Management of real estate on a fee or contract basis,HIGH,
70.10,Activities of head offices; management consultancy activities,Activities of head offices,LOW,
70.21,Activities of head offices; management consultancy activities,Public relations and communication activities,LOW,
71.20,Architectural and engineering activities; technical testing and analysis,Technical testing and analysis,LOW,
72.11,Scientific research and development,Research and experimental development on biotechnology,MEDIUM,
72.19,Scientific research and development,Other research and experimental development on natural sciences and engineering,LOW,
72.20,Scientific research and development,Research and experimental development on social sciences and humanities,LOW,
73.11,Advertising and market research,Advertising agencies,LOW,
73.12,Advertising and market research,Media representation,LOW,
73.20,Advertising and market research,Market research and public opinion polling,LOW,
74.10,"Other professional, scientific and technical activities",Specialised design activities,LOW,
74.30,"Other professional, scientific and technical activities",Translation and interpretation activities,MEDIUM,
75.00,Veterinary activities,Veterinary activities,LOW,
77.11,Rental and leasing activities,Renting and leasing of cars and light motor vehicles,HIGH,
77.12,Rental and leasing activities,Renting and leasing of trucks,LOW,
77.21,Rental and leasing activities,Renting and leasing of recreational and sports goods,LOW,
77.22,Rental and leasing activities,Renting of video tapes and disks,LOW,
77.31,Rental and leasing activities,Renting and leasing of agricultural machinery and equipment,LOW,
77.32,Rental and leasing activities,Renting and leasing of construction and civil engineering machinery and equipment,LOW,
77.33,Rental and leasing activities,Renting and leasing of office machinery and equipment (including computers),LOW,
77.39,Rental and leasing activities,"Renting and leasing of other machinery, equipment and tangible goods n.e.c.",MEDIUM,
77.40,Rental and leasing activities,"Leasing of intellectual property and similar products, except copyrighted works",LOW,
78.20,Employment activities,Temporary employment agency activities,MEDIUM,
78.30,Employment activities,Other human resources provision,MEDIUM,
79.11,"Travel agency, tour operator and other reservation service and related activities",Travel agency activities,LOW,
79.12,"Travel agency, tour operator and other reservation service and related activities",Tour operator activities,LOW,
49.50,Land transport and transport via pipelines,Transport via pipeline,AUTO-HIGH,
80.20,Security and investigation activities,Security systems service activities,LOW,
80.30,Security and investigation activities,Investigation activities,LOW,
81.10,Services to buildings and landscape activities,Combined facilities support activities,LOW,
81.21,Services to buildings and landscape activities,General cleaning of buildings,MEDIUM,
81.30,Services to buildings and landscape activities,Landscape Service Activities,MEDIUM,
82.11,"Office administrative, office support and other business support activities",Combined office administrative service activities,LOW,
82.19,"Office administrative, office support and other business support activities","Photocopying, document preparation and other specialised office support activities",LOW,
82.20,"Office administrative, office support and other business support activities",Activities of call centres,LOW,
82.92,"Office administrative, office support and other business support activities",Packaging activities,MEDIUM,
82.99,"Office administrative, office support and other business support activities",Other business support service activities n.e.c.,MEDIUM,
84.11,Public administration and defence; compulsory social security,General public administration activities,MEDIUM,
84.12,Public administration and defence; compulsory social security,"Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security",LOW,
84.13,Public administration and defence; compulsory social security,Regulation of and contribution to more efficient operation of businesses,LOW,
84.21,Public administration and defence; compulsory social security,Foreign affairs,AUTO-HIGH,
26.11,"Manufacture of computer, electronic and optical products",Manufacture of electronic components,HIGH,
84.23,Public administration and defence; compulsory social security,Justice and judicial activities,LOW,
84.24,Public administration and defence; compulsory social security,Public order and safety activities,LOW,
84.25,Public administration and defence; compulsory social security,Fire service activities,LOW,
84.30,Public administration and defence; compulsory social security,Compulsory social security activities,LOW,
85.10,Education,Pre-primary education,LOW,
85.20,Education,Primary education,LOW,
85.31,Education,General secondary education,LOW,
85.32,Education,Technical and vocational secondary education,LOW,
85.41,Education,Post-secondary non-tertiary education,LOW,
85.51,Education,Sports and recreation education,LOW,
85.52,Education,Cultural education,LOW,
85.53,Education,Driving school activities,LOW,
85.59,Education,Other education n.e.c.,MEDIUM,
85.60,Education,Educational support activities,LOW,
86.21,Human health activities,General medical practice activities,LOW,
86.22,Human health activities,Specialist medical practice activities,LOW,
86.23,Human health activities,Dental practice activities,LOW,
86.90,Human health activities,Other human health activities,MEDIUM,
26.20,"Manufacture of computer, electronic and optical products",Manufacture of computers and peripheral equipment,HIGH,
08.11,Other mining and quarrying,"Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate",MEDIUM,
27.90,Manufacture of electrical equipment,Manufacture of other electrical equipment,MEDIUM,
84.22,Public administration and defence; compulsory social security,Defence activities,AUTO-HIGH,
46.14,"Wholesale trade, except of motor vehicles and motorcycles","Agents involved in the sale of machinery, industrial equipment, ships and aircraft",HIGH,
88.91,Social work activities without accommodation,Child day-care activities,LOW,
88.99,Social work activities without accommodation,Other social work activities without accommodation n.e.c.,LOW,
90.01,"Creative, arts and entertainment activities",Performing arts,LOW,
90.02,"Creative, arts and entertainment activities",Support activities to performing arts,LOW,
90.03,"Creative, arts and entertainment activities",Artistic creation,LOW,
90.04,"Creative, arts and entertainment activities",Operation of arts facilities,LOW,
91.02,"Libraries, archives, museums and other cultural activities",Museum activities,LOW,
91.03,"Libraries, archives, museums and other cultural activities",Operation of historical sites and buildings and similar visitor attractions,LOW,
91.04,"Libraries, archives, museums and other cultural activities",Botanical and zoological gardens and nature reserve activities,MEDIUM,
46.75,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of chemical products,HIGH,
93.11,Sports activities and amusement and recreation activities,Operation of sports facilities,LOW,
93.12,Sports activities and amusement and recreation activities,Activities of sport clubs,MEDIUM,
93.13,Sports activities and amusement and recreation activities,Fitness facilities,LOW,
93.21,Sports activities and amusement and recreation activities,Activities of amusement parks and theme parks,LOW,
93.29,Sports activities and amusement and recreation activities,Other amusement and recreation activities N.E.C.,MEDIUM,
94.11,Activities of membership organisations,Activities of business and employers membership organisations,LOW,
94.12,Activities of membership organisations,Activities of professional membership organisations,LOW,
94.20,Activities of membership organisations,Activities of trade unions,LOW,
61.90,Telecommunications,Other telecommunications activities,HIGH,
94.92,Activities of membership organisations,Activities of political organisations,HIGH,
94.99,Activities of membership organisations,Activities of other membership organisations n.e.c.,MEDIUM,
95.11,Repair of computers and personal and household goods,Repair of computers and peripheral equipment,LOW,
95.12,Repair of computers and personal and household goods,Repair of communication equipment,LOW,
95.21,Repair of computers and personal and household goods,Repair of consumer electronics,LOW,
95.22,Repair of computers and personal and household goods,Repair of household appliances and home and garden equipment,LOW,
95.23,Repair of computers and personal and household goods,Repair of footwear and leather goods,LOW,
95.24,Repair of computers and personal and household goods,Repair of furniture and home furnishings,LOW,
95.25,Repair of computers and personal and household goods,"Repair of watches, clocks and jewellery",LOW,
95.29,Repair of computers and personal and household goods,Repair of other personal and household goods,LOW,
96.01,Other personal service activities,Washing and (dry-)cleaning of textile and fur products,LOW,
96.02,Other personal service activities,Hairdressing and other beauty treatment,MEDIUM,
96.03,Other personal service activities,Funeral and related activities,LOW,
96.04,Other personal service activities,Physical well-being activities,LOW,
26.30/9,"Manufacture of computer, electronic and optical products",Manufacture of communication equipment (other than telegraph and telephone apparatus and equipment),HIGH,
97.00,Activities of households as employers of domestic personnel,Activities of households as employers of domestic personnel,HIGH,
98.10,Undifferentiated goods- and services-producing activities of private households for own use,Undifferentiated goods-producing activities of private households for own use,LOW,
98.20,Undifferentiated goods- and services-producing activities of private households for own use,Undifferentiated service-producing activities of private households for own use,LOW,
99.00,Activities of extraterritorial organisations and bodies,Activities of extraterritorial organisations and bodies,AUTO-HIGH,
26.12,"Manufacture of computer, electronic and optical products",Manufacture of loaded electronic boards,LOW,
01.62/1,Support activities to agriculture and post-harvest crop activities,Farm animal boarding and care,LOW,
01.62/9,Support activities to agriculture and post-harvest crop activities,Support activities for animal production (other than farm animal boarding and care) n.e.c.,LOW,
08.12,Other mining and quarrying,Operation of gravel and sand pits; mining of clays and kaolin,MEDIUM,
92.00,Gambling and betting activities,Gambling and betting activities,AUTO-HIGH,
10.51/1,Manufacture of food products,Liquid milk and cream production,MEDIUM,
10.51/2,Manufacture of food products,Butter and cheese production,MEDIUM,
10.51/9,Manufacture of food products,"Manufacture of milk products (other than liquid milk and cream, butter, cheese) n.e.c.",MEDIUM,
10.61/1,Manufacture of food products,Grain milling,LOW,
10.61/2,Manufacture of food products,Manufacture of breakfast cereals and cereals-based foods,MEDIUM,
10.82/1,Manufacture of food products,"Manufacture of cocoa, and chocolate confectionery",LOW,
10.82/2,Manufacture of food products,Manufacture of sugar confectionery,MEDIUM,
10.83/1,Manufacture of food products,Tea processing,LOW,
10.83/2,Manufacture of food products,Production of coffee and coffee substitutes,LOW,
13.92/1,Manufacture of textiles,Manufacture of soft furnishings,LOW,
13.92/2,Manufacture of textiles,"Manufacture of canvas goods, sacks etc.",LOW,
13.92/3,Manufacture of textiles,Manufacture of household textiles (other than soft furnishings of 13.92/1),LOW,
13.93/1,Manufacture of textiles,Manufacture of woven or tufted carpets and rugs,LOW,
13.93/9,Manufacture of textiles,Manufacture of carpets and rugs (other than woven or tufted) n.e.c.,LOW,
14.13/1,Manufacture of wearing apparel,Manufacture of men's outerwear other than leather clothes and workwear,LOW,
14.13/2,Manufacture of wearing apparel,"Manufacture of women's outerwear, other than leather clothes and workwear",LOW,
14.14/1,Manufacture of wearing apparel,Manufacture of men's underwear,LOW,
14.14/2,Manufacture of wearing apparel,Manufacture of women's underwear,LOW,
17.21/1,Manufacture of paper and paper products,Manufacture of corrugated paper and paperboard; manufacture of sacks and bags of paper,LOW,
17.21/9,Manufacture of paper and paper products,Manufacture of paper and paperboard containers other than sacks and bags,LOW,
17AA,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of UK investment tr,MEDIUM,
17AB,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of UK money market,MEDIUM,
17AC,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of UK insurance com,MEDIUM,
17AD,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of UK individuals,MEDIUM,
17AE,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of any other UK res,MEDIUM,
17AF,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of non-resident cli,MEDIUM,
17AG,,FINANCIAL MANGMNT AUXILIARY ACTIVITIES-Fund Managers acting on behalf of any other deposi,MEDIUM,
18.12/1,Printing and reproduction of recorded media,Manufacture of printed labels,LOW,
18.12/9,Printing and reproduction of recorded media,Printing (other than printing of newspapers and printing on labels and tags) n.e.c.,LOW,
18.20/1,Printing and reproduction of recorded media,Reproduction of sound recording,LOW,
18.20/2,Printing and reproduction of recorded media,Reproduction of video recording,LOW,
18.20/3,Printing and reproduction of recorded media,Reproduction of computer media,LOW,
19.20/1,Manufacture of coke and refined petroleum products,Mineral oil refining,AUTO-HIGH,
19.20/9,Manufacture of coke and refined petroleum products,Other treatment of petroleum products (excluding mineral oil refining/petrochemicals manufacture),MEDIUM,
20.30/1,Manufacture of chemicals and chemical products,"Manufacture of paints, varnishes and similar coatings, mastics and sealants",LOW,
20.30/2,Manufacture of chemicals and chemical products,Manufacture of printing ink,LOW,
20.41/1,Manufacture of chemicals and chemical products,Manufacture of soap and detergents,LOW,
20.41/2,Manufacture of chemicals and chemical products,Manufacture of cleaning and polishing preparations,LOW,
26.51/1,"Manufacture of computer, electronic and optical products","Manufacture of electronic instruments and appliances for measuring, testing, and navigation, except industrial process control equipment",HIGH,
28.99,Manufacture of machinery and equipment n.e.c.,Manufacture of other special-purpose machinery n.e.c.,HIGH,
30.11,Manufacture of other transport equipment,Building of ships and floating structures,HIGH,
26.51/2,"Manufacture of computer, electronic and optical products",Manufacture of electronic industrial process control equipment,AUTO-HIGH,
26.51/3,"Manufacture of computer, electronic and optical products","Manufacture of non-electronic instruments and appliances for measuring, testing and navigation, except industrial process control equipment",AUTO-HIGH,
26.51/4,"Manufacture of computer, electronic and optical products",Manufacture of non-electronic industrial process control equipment,LOW,
64.30/3,"Financial service activities, except insurance and pension funding",Activities of venture and development capital companies,AUTO-HIGH,
26.70/2,"Manufacture of computer, electronic and optical products",Manufacture of photographic and cinematographic equipment,LOW,
30.30,Manufacture of other transport equipment,Manufacture of air and spacecraft and related machinery,HIGH,
28.13/2,Manufacture of machinery and equipment n.e.c.,Manufacture of compressors,LOW,
28.30/1,Manufacture of machinery and equipment n.e.c.,Manufacture of agricultural tractors,LOW,
28.30/2,Manufacture of machinery and equipment n.e.c.,Manufacture of agricultural and forestry machinery (other than agricultural tractors),LOW,
28.92/1,Manufacture of machinery and equipment n.e.c.,Manufacture of machinery for mining,LOW,
28.92/2,Manufacture of machinery and equipment n.e.c.,Manufacture of earthmoving equipment,LOW,
28.92/3,Manufacture of machinery and equipment n.e.c.,Manufacture of equipment for concrete crushing and screening roadworks,LOW,
29.20/1,"Manufacture of motor vehicles, trailers and semi-trailers",Manufacture of bodies (coachwork) for motor vehicles (except caravans),LOW,
29.20/2,"Manufacture of motor vehicles, trailers and semi-trailers",Manufacture of trailers and semi-trailers,LOW,
29.20/3,"Manufacture of motor vehicles, trailers and semi-trailers",Manufacture of caravans,LOW,
32.40/1,Other manufacturing,Manufacture of professional and arcade games and toys,LOW,
32.40/9,Other manufacturing,Manufacture of games and toys (other than professional and arcade games and toys) n.e.c.,LOW,
41.20/1,Construction of buildings,Construction of commercial buildings,MEDIUM,
41.20/2,Construction of buildings,Construction of domestic buildings,MEDIUM,
43.34/1,Specialised construction activities,Painting,MEDIUM,
43.34/2,Specialised construction activities,Glazing,LOW,
43.99/1,Specialised construction activities,Scaffold erection,MEDIUM,
43.99/9,Specialised construction activities,Specialised construction activities (other than scaffold erection) n.e.c.,MEDIUM,
45.11/1,Wholesale and retail trade and repair of motor vehicles and motorcycles,Sale of new cars and light motor vehicles,HIGH,
45.11/2,Wholesale and retail trade and repair of motor vehicles and motorcycles,Sale of used cars and light motor vehicles,HIGH,
46.34/1,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of fruit and vegetable juices, mineral waters and soft drinks",MEDIUM,
46.34/2,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of wine, beer, spirits and other alcoholic beverages",MEDIUM,
46.43/1,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of gramophone records, audio tapes, compact discs and video tapes and of the equipment on which these are played",LOW,
46.43/9,"Wholesale trade, except of motor vehicles and motorcycles","Wholesale of radio and television goods and of electrical household appliances (other than of gramophone records, audio tapes, compact discs and video tapes and the equipment on which these are played) n.e.c.",LOW,
46.49/1,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of musical instruments,LOW,
46.49/9,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of household goods (other than musical instruments) n.e.c.,LOW,
05.10/1,Mining of coal and lignite,Mining of hard coal from deep coal mines (underground mining),AUTO-HIGH,
46.71/9,"Wholesale trade, except of motor vehicles and motorcycles",Wholesale of fuels and related products (other than petroleum and petroleum products),LOW,
47.42/1,"Retail trade, except of motor vehicles and motorcycles",Retail sale of mobile telephones in specialised stores,MEDIUM,
26.70/1,"Manufacture of computer, electronic and optical products",Manufacture of optical precision instruments,HIGH,
47.59/1,"Retail trade, except of motor vehicles and motorcycles",Retail sale of musical instruments and scores in specialised stores,LOW,
47.59/9,"Retail trade, except of motor vehicles and motorcycles","Retail sale of furniture, lighting equipment and other household articles (other than musical instruments) n.e.c., in specialised stores",LOW,
47.72/1,"Retail trade, except of motor vehicles and motorcycles",Retail sale of footwear in specialised stores,LOW,
47.72/2,"Retail trade, except of motor vehicles and motorcycles",Retail sale of leather goods in specialised stores,LOW,
47.74/1,"Retail trade, except of motor vehicles and motorcycles",Retail sale of hearing aids in specialised stores,LOW,
47.74/9,"Retail trade, except of motor vehicles and motorcycles","Retail sale of medical and orthopaedic goods (other than hearing aids) n.e.c., in specialised stores",LOW,
05.10/2,Mining of coal and lignite,Mining of hard coal from open cast coal working (surface mining),AUTO-HIGH,
47.78/2,"Retail trade, except of motor vehicles and motorcycles",Retail sale by opticians,LOW,
25.30,"Manufacture of fabricated metal products, except machinery and equipment","Manufacture of steam generators, except central heating hot water boilers",HIGH,
24.54,Manufacture of basic metals,Casting of other non-ferrous metals,LOW,
47.79/9,"Retail trade, except of motor vehicles and motorcycles",Retail sale of second-hand goods (other than antiques and antique books) in stores,HIGH,
49.31/1,Land transport and transport via pipelines,"Urban, suburban or metropolitan area passenger railway transportation by underground, metro and similar systems",LOW,
49.31/9,Land transport and transport via pipelines,"Urban, suburban or metropolitan area passenger land transport other than railway transportation by underground, metro and similar systems",LOW,
51.10/1,Air transport,Scheduled passenger air transport,MEDIUM,
51.10/2,Air transport,Non-scheduled passenger air transport,MEDIUM,
52.10/1,Warehousing and support activities for transportation,Operation of warehousing and storage facilities for water transport activities of division 50,MEDIUM,
52.10/2,Warehousing and support activities for transportation,Operation of warehousing and storage facilities for air transport activities of division 51,MEDIUM,
52.10/3,Warehousing and support activities for transportation,Operation of warehousing and storage facilities for land transport activities of division 49,MEDIUM,
52.21/1,Warehousing and support activities for transportation,Operation of rail freight terminals,MEDIUM,
52.21/2,Warehousing and support activities for transportation,Operation of rail passenger facilities at railway stations,MEDIUM,
52.21/3,Warehousing and support activities for transportation,Operation of bus and coach passenger facilities at bus and coach stations,MEDIUM,
52.21/9,Warehousing and support activities for transportation,"Other service activities incidental to land transportation, n.e.c. (not including operation of rail freight terminals, passenger facilities at railway stations or passenger facilities at bus and coach stations)",MEDIUM,
52.24/1,Warehousing and support activities for transportation,Cargo handling for water transport activities of division 50,MEDIUM,
52.24/2,Warehousing and support activities for transportation,Cargo handling for air transport activities of division 51,MEDIUM,
52.24/3,Warehousing and support activities for transportation,Cargo handling for land transport activities of division 49,MEDIUM,
53.20/1,Warehousing and support activities for transportation,Licensed Carriers,LOW,
53.20/2,Warehousing and support activities for transportation,Unlicensed Carriers,LOW,
55.20/1,Accommodation,Holiday centres and villages,LOW,
55.20/2,Accommodation,Youth hostels,LOW,
55.20/9,Accommodation,Other holiday and other short-stay accommodation (not including holiday centres and villages or youth hostels) n.e.c.,LOW,
56.10/1,Food and beverage service activities,Licensed restaurants,MEDIUM,
56.10/2,Food and beverage service activities,Unlicensed restaurants and cafes,MEDIUM,
56.10/3,Food and beverage service activities,Take away food shops and mobile food stands,MEDIUM,
56.30/1,Food and beverage service activities,Licensed clubs,LOW,
56.30/2,Food and beverage service activities,Public houses and bars,LOW,
58.14/1,Publishing activities,Publishing of learned journals,LOW,
58.14/2,Publishing activities,"Publishing of consumer, business and professional journals and periodicals",LOW,
59.11/1,"Motion picture, video and television programme production, sound recording and music publishing activites",Motion picture production activities,MEDIUM,
59.11/2,"Motion picture, video and television programme production, sound recording and music publishing activites",Video production activities,MEDIUM,
59.11/3,"Motion picture, video and television programme production, sound recording and music publishing activites",Television programme production activities,LOW,
59.13/1,"Motion picture, video and television programme production, sound recording and music publishing activites",Motion picture distribution activities,LOW,
59.13/2,"Motion picture, video and television programme production, sound recording and music publishing activites",Video distribution activities,LOW,
59.13/3,"Motion picture, video and television programme production, sound recording and music publishing activites",Television programme distribution activities,LOW,
62.01/1,"Computer programming, consultancy and related activities",Ready-made interactive leisure and entertainment software development,LOW,
62.01/2,"Computer programming, consultancy and related activities",Business and domestic software development,LOW,
20.20,Manufacture of chemicals and chemical products,Manufacture of pesticides and other agrochemical products,HIGH,
64.19/2,"Financial service activities, except insurance and pension funding",Building societies,LOW,
64.20/1,"Financial service activities, except insurance and pension funding",Activities of agricultural holding companies,LOW,
64.20/2,"Financial service activities, except insurance and pension funding",Activities of production holding companies,LOW,
64.20/3,"Financial service activities, except insurance and pension funding",Activities of construction holding companies,MEDIUM,
64.20/4,"Financial service activities, except insurance and pension funding",Activities of distribution holding companies,LOW,
64.20/5,"Financial service activities, except insurance and pension funding",Activities of financial services holding companies,LOW,
64.20/9,"Financial service activities, except insurance and pension funding","Activities of other holding companies (not including agricultural, production, construction, distribution and financial services holding companies) n.e.c.",LOW,
64.30/1,"Financial service activities, except insurance and pension funding",Activities of investment trusts,LOW,
64.30/2,"Financial service activities, except insurance and pension funding",Activities of unit trusts,LOW,
64.30/4,"Financial service activities, except insurance and pension funding",Activities of open-ended investment companies,MEDIUM,
64.30/5,"Financial service activities, except insurance and pension funding",Activities of property unit trusts,HIGH,
64.30/6,"Financial service activities, except insurance and pension funding",Activities of real estate investment trusts,HIGH,
64.92/1,"Financial service activities, except insurance and pension funding",Credit granting by non-deposit taking finance houses and other specialist consumer credit grantors,AUTO-HIGH,
64.92/2,"Financial service activities, except insurance and pension funding",Activities of mortgage finance companies,LOW,
64.92/9,"Financial service activities, except insurance and pension funding",Other credit granting (not including credit granting by non-deposit taking finance houses and other specialist consumer credit grantors and activities of mortgage finance companies) n.e.c.,AUTO-HIGH,
64.99/1,"Financial service activities, except insurance and pension funding",Security dealing on own account,LOW,
64.99/2,"Financial service activities, except insurance and pension funding",Factoring,HIGH,
28.11,Manufacture of machinery and equipment n.e.c.,"Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",HIGH,
65.20/1,"Insurance, reinsurance and pension funding, except compulsory social security",Life reinsurance,LOW,
65.20/2,"Insurance, reinsurance and pension funding, except compulsory social security",Non-life reinsurance,LOW,
68.20/1,Real estate activities,Renting and operating of Housing Association real estate,MEDIUM,
68.20/2,Real estate activities,Letting and operating of conference and exhibition centres,LOW,
68.20/9,Real estate activities,Letting and operating of own or leased real estate (other than Housing Association real estate and conference and exhibition services) n.e.c.,HIGH,
69.10/1,Legal and accounting activities,Barristers at law,LOW,
69.10/2,Legal and accounting activities,Solicitors,HIGH,
69.10/9,Legal and accounting activities,Activities of patent and copyright agents; other legal activities (other than those of barristers and solicitors) n.e.c.,LOW,
69.20/1,Legal and accounting activities,"Accounting, and auditing activities",HIGH,
69.20/2,Legal and accounting activities,Bookkeeping activities,HIGH,
69.20/3,Legal and accounting activities,Tax consultancy,HIGH,
70.22/1,Activities of head offices; management consultancy activities,Financial management,HIGH,
70.22/9,Activities of head offices; management consultancy activities,Management consultancy activities (other than financial management),LOW,
71.11/1,Architectural and engineering activities; technical testing and analysis,Architectural activities,LOW,
71.11/2,Architectural and engineering activities; technical testing and analysis,Urban planning and landscape architectural activities,MEDIUM,
71.12/1,Architectural and engineering activities; technical testing and analysis,Engineering design activities for industrial process and production,LOW,
71.12/2,Architectural and engineering activities; technical testing and analysis,Engineering related scientific and technical consulting activities,LOW,
71.12/9,Architectural and engineering activities; technical testing and analysis,Other engineering activities (not including engineering design for industrial process and production or engineering related scientific and technical consulting activities),LOW,
74.20/1,"Other professional, scientific and technical activities",Portrait photographic activities,MEDIUM,
74.20/2,"Other professional, scientific and technical activities",Other specialist photography (not including portrait photography),LOW,
74.20/3,"Other professional, scientific and technical activities",Film processing,LOW,
74.20/9,"Other professional, scientific and technical activities",Other photographic activities (not including portrait and other specialist photography and film processing) n.e.c.,LOW,
74.90/1,"Other professional, scientific and technical activities",Environmental consulting activities,LOW,
74.90/2,"Other professional, scientific and technical activities",Quantity surveying activities,LOW,
74.90/9,"Other professional, scientific and technical activities","Other professional, scientific and technical activities (not including environmental consultancy or quantity surveying) n.e.c.",MEDIUM,
77.29/1,Rental and leasing activities,Renting and leasing of media entertainment equipment,LOW,
77.29/9,Rental and leasing activities,Renting and leasing of other personal and household goods (other than media entertainment equipment),LOW,
77.34/1,Rental and leasing activities,Renting and leasing of passenger water transport equipment,LOW,
77.34/2,Rental and leasing activities,Renting and leasing of freight water transport equipment,LOW,
77.35/1,Rental and leasing activities,Renting and leasing of passenger air transport equipment,LOW,
77.35/2,Rental and leasing activities,Renting and leasing of freight air transport equipment,LOW,
78.10/1,Employment activities,"Motion picture, television and other theatrical casting",LOW,
78.10/9,Employment activities,Activities of employment placement agencies (other than motion picture television and other theatrical casting) n.e.c.,MEDIUM,
79.90/1,"Travel agency, tour operator and other reservation service and related activities",Activities of tourist guides,LOW,
79.90/9,"Travel agency, tour operator and other reservation service and related activities",Other reservation service activities (not including activities of tourist guides),LOW,
81.22/1,Services to buildings and landscape activities,Window cleaning services,LOW,
81.22/2,Services to buildings and landscape activities,Specialised cleaning services,MEDIUM,
81.22/3,Services to buildings and landscape activities,Furnace and chimney cleaning services,LOW,
81.22/9,Services to buildings and landscape activities,"Building and industrial cleaning activities (other than window cleaning, specialised cleaning and furnace and chimney cleaning services) n.e.c.",MEDIUM,
81.29/1,Services to buildings and landscape activities,Disinfecting and extermination services,LOW,
81.29/9,Services to buildings and landscape activities,Cleaning services (other than disinfecting and extermination services) n.e.c.,MEDIUM,
82.30/1,"Office administrative, office support and other business support activities",Activities of exhibition and fair organizers,LOW,
82.30/2,"Office administrative, office support and other business support activities",Activities of conference organizers,LOW,
82.91/1,"Office administrative, office support and other business support activities",Activities of collection agencies,LOW,
82.91/2,"Office administrative, office support and other business support activities",Activities of credit bureaus,LOW,
85.42/1,Education,First-degree level higher education,LOW,
85.42/2,Education,Post-graduate level higher education,LOW,
86.10/1,Human health activities,Hospital activities,LOW,
86.10/2,Human health activities,Medical nursing home activities,LOW,
91.01/1,"Libraries, archives, museums and other cultural activities",Library activities,LOW,
91.01/2,"Libraries, archives, museums and other cultural activities",Archive activities,LOW,
93.19/1,Sports activities and amusement and recreation activities,Activities of racehorse owners,MEDIUM,
93.19/9,Sports activities and amusement and recreation activities,Other sports activities (not including activities of racehorse owners) n.e.c.,MEDIUM,
NOT_FOUND,,Data Not Recognised,HIGH,
NULL,,MISSING DATA,HIGH,
`;
const entityTypesCsv = `
code,description,risk_weight
01,Private Limited Company,MEDIUM
02,Sole Trader,MEDIUM
03,Limited Liability Partnership,MEDIUM
04,Clubs,HIGH
05,Charity,HIGH
06,Association / Society,HIGH
07,Public Limited Company (PLC),MEDIUM
09,Partnership,HIGH
10,Trust,HIGH
12,Pension Schemes,LOW
14,Public Sector Bodies,LOW
16,Outlet,HIGH
99,Missing Data,HIGH
`

let entityTypes: FormOptionModel[];
let industryTypes: FormOptionModel[];

export class MenuOptionsMock implements MenuOptionsApi {
    async getCountryList(): Promise<FormOptionModel[]> {
        return [
            {text: 'Afghanistan', value: 'AF'},
            {text: 'Åland Islands', value: 'AX'},
            {text: 'Albania', value: 'AL'},
            {text: 'Algeria', value: 'DZ'},
            {text: 'American Samoa', value: 'AS'},
            {text: 'AndorrA', value: 'AD'},
            {text: 'Angola', value: 'AO'},
            {text: 'Anguilla', value: 'AI'},
            {text: 'Antarctica', value: 'AQ'},
            {text: 'Antigua and Barbuda', value: 'AG'},
            {text: 'Argentina', value: 'AR'},
            {text: 'Armenia', value: 'AM'},
            {text: 'Aruba', value: 'AW'},
            {text: 'Australia', value: 'AU'},
            {text: 'Austria', value: 'AT'},
            {text: 'Azerbaijan', value: 'AZ'},
            {text: 'Bahamas', value: 'BS'},
            {text: 'Bahrain', value: 'BH'},
            {text: 'Bangladesh', value: 'BD'},
            {text: 'Barbados', value: 'BB'},
            {text: 'Belarus', value: 'BY'},
            {text: 'Belgium', value: 'BE'},
            {text: 'Belize', value: 'BZ'},
            {text: 'Benin', value: 'BJ'},
            {text: 'Bermuda', value: 'BM'},
            {text: 'Bhutan', value: 'BT'},
            {text: 'Bolivia', value: 'BO'},
            {text: 'Bosnia and Herzegovina', value: 'BA'},
            {text: 'Botswana', value: 'BW'},
            {text: 'Bouvet Island', value: 'BV'},
            {text: 'Brazil', value: 'BR'},
            {text: 'British Indian Ocean Territory', value: 'IO'},
            {text: 'Brunei Darussalam', value: 'BN'},
            {text: 'Bulgaria', value: 'BG'},
            {text: 'Burkina Faso', value: 'BF'},
            {text: 'Burundi', value: 'BI'},
            {text: 'Cambodia', value: 'KH'},
            {text: 'Cameroon', value: 'CM'},
            {text: 'Canada', value: 'CA'},
            {text: 'Cape Verde', value: 'CV'},
            {text: 'Cayman Islands', value: 'KY'},
            {text: 'Central African Republic', value: 'CF'},
            {text: 'Chad', value: 'TD'},
            {text: 'Chile', value: 'CL'},
            {text: 'China', value: 'CN'},
            {text: 'Christmas Island', value: 'CX'},
            {text: 'Cocos (Keeling) Islands', value: 'CC'},
            {text: 'Colombia', value: 'CO'},
            {text: 'Comoros', value: 'KM'},
            {text: 'Congo', value: 'CG'},
            {text: 'Congo, The Democratic Republic of the', value: 'CD'},
            {text: 'Cook Islands', value: 'CK'},
            {text: 'Costa Rica', value: 'CR'},
            {text: 'Cote D\'Ivoire', value: 'CI'},
            {text: 'Croatia', value: 'HR'},
            {text: 'Cuba', value: 'CU'},
            {text: 'Cyprus', value: 'CY'},
            {text: 'Czech Republic', value: 'CZ'},
            {text: 'Denmark', value: 'DK'},
            {text: 'Djibouti', value: 'DJ'},
            {text: 'Dominica', value: 'DM'},
            {text: 'Dominican Republic', value: 'DO'},
            {text: 'Ecuador', value: 'EC'},
            {text: 'Egypt', value: 'EG'},
            {text: 'El Salvador', value: 'SV'},
            {text: 'Equatorial Guinea', value: 'GQ'},
            {text: 'Eritrea', value: 'ER'},
            {text: 'Estonia', value: 'EE'},
            {text: 'Ethiopia', value: 'ET'},
            {text: 'Falkland Islands (Malvinas)', value: 'FK'},
            {text: 'Faroe Islands', value: 'FO'},
            {text: 'Fiji', value: 'FJ'},
            {text: 'Finland', value: 'FI'},
            {text: 'France', value: 'FR'},
            {text: 'French Guiana', value: 'GF'},
            {text: 'French Polynesia', value: 'PF'},
            {text: 'French Southern Territories', value: 'TF'},
            {text: 'Gabon', value: 'GA'},
            {text: 'Gambia', value: 'GM'},
            {text: 'Georgia', value: 'GE'},
            {text: 'Germany', value: 'DE'},
            {text: 'Ghana', value: 'GH'},
            {text: 'Gibraltar', value: 'GI'},
            {text: 'Greece', value: 'GR'},
            {text: 'Greenland', value: 'GL'},
            {text: 'Grenada', value: 'GD'},
            {text: 'Guadeloupe', value: 'GP'},
            {text: 'Guam', value: 'GU'},
            {text: 'Guatemala', value: 'GT'},
            {text: 'Guernsey', value: 'GG'},
            {text: 'Guinea', value: 'GN'},
            {text: 'Guinea-Bissau', value: 'GW'},
            {text: 'Guyana', value: 'GY'},
            {text: 'Haiti', value: 'HT'},
            {text: 'Heard Island and Mcdonald Islands', value: 'HM'},
            {text: 'Holy See (Vatican City State)', value: 'VA'},
            {text: 'Honduras', value: 'HN'},
            {text: 'Hong Kong', value: 'HK'},
            {text: 'Hungary', value: 'HU'},
            {text: 'Iceland', value: 'IS'},
            {text: 'India', value: 'IN'},
            {text: 'Indonesia', value: 'ID'},
            {text: 'Iran, Islamic Republic Of', value: 'IR'},
            {text: 'Iraq', value: 'IQ'},
            {text: 'Ireland', value: 'IE'},
            {text: 'Isle of Man', value: 'IM'},
            {text: 'Israel', value: 'IL'},
            {text: 'Italy', value: 'IT'},
            {text: 'Jamaica', value: 'JM'},
            {text: 'Japan', value: 'JP'},
            {text: 'Jersey', value: 'JE'},
            {text: 'Jordan', value: 'JO'},
            {text: 'Kazakhstan', value: 'KZ'},
            {text: 'Kenya', value: 'KE'},
            {text: 'Kiribati', value: 'KI'},
            {text: 'Korea, Democratic People\'S Republic of', value: 'KP'},
            {text: 'Korea, Republic of', value: 'KR'},
            {text: 'Kuwait', value: 'KW'},
            {text: 'Kyrgyzstan', value: 'KG'},
            {text: 'Lao People\'S Democratic Republic', value: 'LA'},
            {text: 'Latvia', value: 'LV'},
            {text: 'Lebanon', value: 'LB'},
            {text: 'Lesotho', value: 'LS'},
            {text: 'Liberia', value: 'LR'},
            {text: 'Libyan Arab Jamahiriya', value: 'LY'},
            {text: 'Liechtenstein', value: 'LI'},
            {text: 'Lithuania', value: 'LT'},
            {text: 'Luxembourg', value: 'LU'},
            {text: 'Macao', value: 'MO'},
            {text: 'Macedonia, The Former Yugoslav Republic of', value: 'MK'},
            {text: 'Madagascar', value: 'MG'},
            {text: 'Malawi', value: 'MW'},
            {text: 'Malaysia', value: 'MY'},
            {text: 'Maldives', value: 'MV'},
            {text: 'Mali', value: 'ML'},
            {text: 'Malta', value: 'MT'},
            {text: 'Marshall Islands', value: 'MH'},
            {text: 'Martinique', value: 'MQ'},
            {text: 'Mauritania', value: 'MR'},
            {text: 'Mauritius', value: 'MU'},
            {text: 'Mayotte', value: 'YT'},
            {text: 'Mexico', value: 'MX'},
            {text: 'Micronesia, Federated States of', value: 'FM'},
            {text: 'Moldova, Republic of', value: 'MD'},
            {text: 'Monaco', value: 'MC'},
            {text: 'Mongolia', value: 'MN'},
            {text: 'Montserrat', value: 'MS'},
            {text: 'Morocco', value: 'MA'},
            {text: 'Mozambique', value: 'MZ'},
            {text: 'Myanmar', value: 'MM'},
            {text: 'Namibia', value: 'NA'},
            {text: 'Nauru', value: 'NR'},
            {text: 'Nepal', value: 'NP'},
            {text: 'Netherlands', value: 'NL'},
            {text: 'Netherlands Antilles', value: 'AN'},
            {text: 'New Caledonia', value: 'NC'},
            {text: 'New Zealand', value: 'NZ'},
            {text: 'Nicaragua', value: 'NI'},
            {text: 'Niger', value: 'NE'},
            {text: 'Nigeria', value: 'NG'},
            {text: 'Niue', value: 'NU'},
            {text: 'Norfolk Island', value: 'NF'},
            {text: 'Northern Mariana Islands', value: 'MP'},
            {text: 'Norway', value: 'NO'},
            {text: 'Oman', value: 'OM'},
            {text: 'Pakistan', value: 'PK'},
            {text: 'Palau', value: 'PW'},
            {text: 'Palestinian Territory, Occupied', value: 'PS'},
            {text: 'Panama', value: 'PA'},
            {text: 'Papua New Guinea', value: 'PG'},
            {text: 'Paraguay', value: 'PY'},
            {text: 'Peru', value: 'PE'},
            {text: 'Philippines', value: 'PH'},
            {text: 'Pitcairn', value: 'PN'},
            {text: 'Poland', value: 'PL'},
            {text: 'Portugal', value: 'PT'},
            {text: 'Puerto Rico', value: 'PR'},
            {text: 'Qatar', value: 'QA'},
            {text: 'Reunion', value: 'RE'},
            {text: 'Romania', value: 'RO'},
            {text: 'Russian Federation', value: 'RU'},
            {text: 'RWANDA', value: 'RW'},
            {text: 'Saint Helena', value: 'SH'},
            {text: 'Saint Kitts and Nevis', value: 'KN'},
            {text: 'Saint Lucia', value: 'LC'},
            {text: 'Saint Pierre and Miquelon', value: 'PM'},
            {text: 'Saint Vincent and the Grenadines', value: 'VC'},
            {text: 'Samoa', value: 'WS'},
            {text: 'San Marino', value: 'SM'},
            {text: 'Sao Tome and Principe', value: 'ST'},
            {text: 'Saudi Arabia', value: 'SA'},
            {text: 'Senegal', value: 'SN'},
            {text: 'Serbia and Montenegro', value: 'CS'},
            {text: 'Seychelles', value: 'SC'},
            {text: 'Sierra Leone', value: 'SL'},
            {text: 'Singapore', value: 'SG'},
            {text: 'Slovakia', value: 'SK'},
            {text: 'Slovenia', value: 'SI'},
            {text: 'Solomon Islands', value: 'SB'},
            {text: 'Somalia', value: 'SO'},
            {text: 'South Africa', value: 'ZA'},
            {text: 'South Georgia and the South Sandwich Islands', value: 'GS'},
            {text: 'Spain', value: 'ES'},
            {text: 'Sri Lanka', value: 'LK'},
            {text: 'Sudan', value: 'SD'},
            {text: 'Suritext', value: 'SR'},
            {text: 'Svalbard and Jan Mayen', value: 'SJ'},
            {text: 'Swaziland', value: 'SZ'},
            {text: 'Sweden', value: 'SE'},
            {text: 'Switzerland', value: 'CH'},
            {text: 'Syrian Arab Republic', value: 'SY'},
            {text: 'Taiwan, Province of China', value: 'TW'},
            {text: 'Tajikistan', value: 'TJ'},
            {text: 'Tanzania, United Republic of', value: 'TZ'},
            {text: 'Thailand', value: 'TH'},
            {text: 'Timor-Leste', value: 'TL'},
            {text: 'Togo', value: 'TG'},
            {text: 'Tokelau', value: 'TK'},
            {text: 'Tonga', value: 'TO'},
            {text: 'Trinidad and Tobago', value: 'TT'},
            {text: 'Tunisia', value: 'TN'},
            {text: 'Turkey', value: 'TR'},
            {text: 'Turkmenistan', value: 'TM'},
            {text: 'Turks and Caicos Islands', value: 'TC'},
            {text: 'Tuvalu', value: 'TV'},
            {text: 'Uganda', value: 'UG'},
            {text: 'Ukraine', value: 'UA'},
            {text: 'United Arab Emirates', value: 'AE'},
            {text: 'United Kingdom', value: 'GB'},
            {text: 'United States', value: 'US'},
            {text: 'United States Minor Outlying Islands', value: 'UM'},
            {text: 'Uruguay', value: 'UY'},
            {text: 'Uzbekistan', value: 'UZ'},
            {text: 'Vanuatu', value: 'VU'},
            {text: 'Venezuela', value: 'VE'},
            {text: 'Viet Nam', value: 'VN'},
            {text: 'Virgin Islands, British', value: 'VG'},
            {text: 'Virgin Islands, U.S.', value: 'VI'},
            {text: 'Wallis and Futuna', value: 'WF'},
            {text: 'Western Sahara', value: 'EH'},
            {text: 'Yemen', value: 'YE'},
            {text: 'Zambia', value: 'ZM'},
            {text: 'Zimbabwe', value: 'ZW'}
        ]
    }

    async getEntityTypes(): Promise<FormOptionModel[]> {
        if (entityTypes) {
            return entityTypes;
        }

        return entityTypes = entityTypesCsv
            .split('\n')
            .map(parseCsv)
            .map(values => ({
                value: '' + values[0],
                text: '' + values[1],
            }))
            .filter(val => val.value !== 'code');
    }

    async getIndustries(): Promise<FormOptionModel[]> {
        if (industryTypes) {
            return industryTypes;
        }

        return industryTypes = industryTypesCsv
            .split('\n')
            .map(parseCsv)
            .map(values => ({
                value: '' + values[0],
                text: '' + values[2],
            }))
            .filter(val => val.value !== 'Code');
    }
}